replicaCount: 1

image:
  repository: alan297/python-app
  pullPolicy: IfNotPresent
  tag: "v4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: python.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

volumes: []
volumeMounts: []
nodeSelector: {}

tolerations: []

affinity: {}
